networks:
  roboshop:
    external: true

volumes:   #equalent to docker volume create mongodb etc...
  mongodb:
    name: mongodb
  redis:
    name: redis
  mysql:
    name: remysqldis
  rabbitmq:
    name: rabbitmq

services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    networks:
      - roboshop
    volumes:
      - source: mongodb
        target: /data/db
        type: volume
  
  catalogue:  
    image: catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
    - mongodb
  
  redis:
    image: redis
    container_name: redis
    networks:
      - roboshop
    volumes:
      - redis:/data
  
  user:
    image: user:v1
    container_name: user
    networks:
      - roboshop
    depends_on:
      - redis
      - mongodb
    
  cart:
    image: cart:v1
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - redis
      - mongodb
      
  mysql:
    image: mysql:v1
    container_name: mysql
    networks:
      - roboshop
    environment:
    - DB_HOST=mysql
    - MYSQL_USER=shipping
    - MYSQL_PASSWORD=RoboShop@1
    - MYSQL_DATABASE=cities
    volumes:
      - mysql:/var/lib/mysql

#if u dont give container-name docker creates automatically like roboshop-docker-cataloge:v1 like that give by default

  shipping:
    image: shipping:v1
    container_name: shipping
    networks:
      - roboshop
    depends_on: 
    - mysql
    - cart

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - roboshop
    environment:
    - RABBITMQ_DEFAULT_USER=roboshop
    - RABBITMQ_DEFAULT_PASS=roboshop123
    volumes:
      - source: rabbitmq
        target: /var/lib/rabbitmq
        type: volume

  payment:
    image: payment:v1
    container_name: payment
    networks:
      - roboshop
    depends_on: 
    - cart
    - user

  web:
    image: web:v1
    container_name: web
    networks:
      - roboshop
    ports:
    - "8080:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment